### ISSUE TITLE
Does this work with ZSH?

### ISSUE THREAD

**Issue by spencerthayer** [lapwat/papeer#16]
+   10:57:57am ﬌ papeer list https://developer.spotify.com/documentation/web-api --selector='#main'
zsh: command not found: papeer

**Comment by lapwat** [comment]
It seems you have not set up Golang properly.

Go to https://go.dev/doc/install
--> Go Installation
--> Select your Operating System

You need to append the Golang `bin` folder to your PATH in `.zshrc`.
