### ISSUE TITLE
[Feature Request] Show source link when storing website

### ISSUE THREAD

**Issue by otoledan** [lapwat/papeer#22]
Having the source link displayed when viewing the epub would help identify websites that don't clearly mark what source they are. This happens often when converting news articles to epub. It could be anywhere in the document -- tho preferably as a subtitle on under the title I think would be the most clear.

**Comment by lapwat** [comment]
Thank you for the feedback. Check out the latest version `v0.8.2`. Does the `--print-url` option solves your issue?
