### ISSUE TITLE
list allows usage of `-l` w/o `-s` while get doesn't

### ISSUE THREAD

**Issue by ljrk0** [lapwat/papeer#4]
The `list` command implicitly allows using no selector and uses the default of `""`.  Get doesn't work when only passing `-l`, nor does it work with passing `-s ""`.  In my case the "default" selector that `get` uses works quite well, but simply spits out a few chapters at the end that I intend to omit.  Using `papeer list -l 5 <uri>` does that, however I cannot do the same with `papeer get -l 5 <uri>`.

I think ideally it should be allowed to use `-l` and others with a default selector.

**Comment by lapwat** [comment]
`get` and `list` options do not work exactly the same.

`list` option implicitly search for one level down.

On the other side, `get` option will retrieve the root page and will not look for subpages. You need to specify at least a `--depth` or `--selector` as the error message suggests:

```txt
> papeer get -l2 https://blog.lapw.at
cannot use limit option if depth/selector is not specified
```

In your case, where you want the selector to be automatically determined, you may use a the `depth` option set to `1`:

```
> papeer get -d1 -l2 https://blog.lapw.at
Markdown saved to "lapw.at's_blog.md"
```

Hope it helps

**Comment by lapwat** [comment]
However, it could be a nice feature to add. When you specify a limit option, it is also implicit that you want to look for one level down.

**Comment by lapwat** [comment]
There was an issue with duplicated lines in the code that increased the `depth` twice.

I took the opportunity to add the feature you requested in this issue in release `0.5.4`.

Now both commands should be accepted and have the same behavior:

```sh
papeer get -d1 -l2 https://blog.lapw.at
papeer get -l2 https://blog.lapw.at
```

**Comment by ljrk0** [comment]
Wow, now I understand both the original issue better and it's already fixed!  I'm more than grateful, what a wonderful tool!
